spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  config:
    import: classpath:redisCache.yml
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 10s

server:
  port: 8080

# MyBatis-Plus 全局通用配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.starshop.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
    send-message-timeout: 10000
  consumer:
    group: my-consumer-group
    message-model: BROADCASTING
    pull-batch-size: 100

# 日志
logging:
  level:
    com.starshop: debug