spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  config:
    import: classpath:redisCache.yml
  datasource:
    url: jdbc:mysql://${starShop.datasource.host}:${starShop.datasource.port}/${starShop.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${starShop.datasource.username}
    password: ${starShop.datasource.password}
    driver-class-name: ${starShop.datasource.driver-class-name}
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
  elasticsearch:
    uris: http://192.168.100.128:9200
    connection-timeout: 5s
    socket-timeout: 10s

server:
  port: 8080

# MyBatis-Plus 全局通用配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.starshop.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

rocketmq:
  name-server: 192.168.100.128:9876
  producer:
    group: my-producer-group
    send-message-timeout: 10000
  consumer:
    group: my-consumer-group
    message-model: BROADCASTING
    pull-batch-size: 100

# 日志
logging:
  level:
    com.starshop: debug